name: simpleFactions
main: com.crossedshadows.simpleFactions.simpleFactions
version: 1.87
permissions:
  simplefactions.sf: {description: Base command, default: true}
  simplefactions.admin: {description: Admin powers, default: false}
commands:
   sf:
      description: This is the base command
      usage: /sf
      permission: simplefactions.sf
      permission-message: You don't have <permission>
   f:
      description: This is the base command alternative
      usage: /sf
      permission: simplefactions.sf
      permission-message: You don't have <permission>